export const RETRIEVE_CATEGORIES = 'RETRIEVE_CATEGORIES';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const RETRIEVE_IMAGES = 'RETRIEVE_IMAGES';
export const ERASE_IMAGES = 'ERASE_IMAGES';
export const IMAGES_LOADING = 'IMAGES_LOADING';
